In [1]:
import time
import matplotlib.pyplot as plt
import numpy as np
import os

### Exercice 1 – Recuit simulé pour le problème du sac à dos 0/1

On vous demande dans cet exercice de programmer un algorithme de recuit simulé pour résoudre le problème
du sac à dos 0/1. Vous testerez votre algorithme sur les données fournies lors des séances précédentes. Vous
comparerez statistiquement (donc en faisant de multiples run de votre algorithme, ce qui est indispensable
quand l’aléatoire intervient) les résultats de votre algorithme avec ceux obtenus par une stratégie déterministe,
consistant à accepter uniquement les solutions améliorantes. Vous pourrez également :

- comparer les solutions obtenues avec les solutions optimales.
- analyser l’impact des différents paramètres de l’algorithme.

Pour générer un voisin à partir d’une solution initiale, plusieurs options pourront être imaginées. Une pos-
sibilité consiste à :

1. Tirer aléatoirement un objet non présent dans le sac
2. Ajouter cet objet
3. Tant que le poids du sac dépasse la capacité maximale :

(a) Tirer aléatoirement un objet présent dans le sac

(b) Supprimer cet objet

In [84]:
def initial_solution(weights, values, wmax):
    W = int(wmax) 
    n = len(weights) 
    list = np.zeros(n)
    result = 0

    while W >= 0:
        i = np.random.randint(n)
        if list[i] == 0:
            list[i] = 1
            W = W - weights[i]
            result = result + values[i]

    list[i] = 0
    W = W + weights[i]
    result = result - values[i]
    return result, W, list

In [261]:
def Knapsack_DA(weights, values, wmax):
    result, W, list = initial_solution(weights, values, wmax)
    n = len(weights)

    # print("resultado inicial = ", result)
    # print(list)

    Best_list = list
    Best_result = result
    Best_W = W

    print(f"{Best_list}, {Best_W}, {Best_result} (Initial)\n")

    for iteration in range(20):
        voisin_list = Best_list
        voisin_result = Best_result
        voisin_W = Best_W
        
        i = np.random.randint(n)
        if voisin_list[i] == 0:
            voisin_list[i] = 1
            voisin_W = voisin_W - weights[i]
            voisin_result = voisin_result + values[i]

            print(f"{voisin_list}, {voisin_W}, {voisin_result} (add{i}, {weights[i]}, {values[i]})")

            while voisin_W < 0:
                j = np.random.randint(n)
                if voisin_list[j] == 1:
                    voisin_list[j] = 0
                    voisin_W = voisin_W + weights[j]
                    voisin_result = voisin_result - values[j]
                    print(f"{voisin_list}, {voisin_W}, {voisin_result} (remove{j}, {weights[j]}, {values[j]})")

            if voisin_result >= Best_result:
                Best_list = voisin_list
                Best_W = voisin_W 
                Best_result = voisin_result

                print(f"{Best_list}, {Best_W}, {Best_result} (New Best)\n")

    return Best_result, Best_list
    

In [2]:
path = "./instances_01_KP/low-dimensional/f10_l-d_kp_20_879" 
dataset = np.loadtxt(path)

n = int(dataset[0][0])
wmax = dataset[0][1]
itens = dataset[1:]

weights = dataset[1:,1]
values = dataset[1:,0]

print(weights)
print(values)

[84. 83. 43.  4. 44.  6. 82. 92. 25. 83. 56. 18. 58. 14. 48. 70. 96. 32.
 68. 92.]
[91. 72. 90. 46. 55.  8. 35. 75. 61. 15. 77. 40. 63. 75. 29. 75. 17. 78.
 40. 44.]


In [271]:
for i in range(1):
    result, list = Knapsack_DA(weights, values, wmax)
    print("resultado final = ", result)
    print(list,"\n")

[1. 1. 1. 1. 1. 0. 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1.], 30.0, 948.0 (Initial)

[1. 1. 1. 1. 1. 0. 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], -38.0, 988.0 (add18, 68.0, 40.0)
[1. 1. 1. 1. 1. 0. 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1.], 58.0, 971.0 (remove16, 96.0, 17.0)
[1. 1. 1. 1. 1. 0. 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1.], 58.0, 971.0 (New Best)

[1. 1. 1. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1.], -25.0, 986.0 (add9, 83.0, 15.0)
[1. 1. 1. 1. 0. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1.], 19.0, 931.0 (remove4, 44.0, 55.0)
[1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1.], -34.0, 1046.0 (add7, 92.0, 75.0)
[1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1.], -2.0, 968.0 (remove17, 32.0, 78.0)
[1. 1. 1. 1. 0. 0. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1.], 23.0, 907.0 (remove8, 25.0, 61.0)
[1. 1. 1. 1. 1. 0. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1.], 14.0, 1026.0 (add4, 44.0, 55.0)
[1. 1. 1. 1. 1. 0. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0. 